# Generated by Django 4.1.13 on 2024-05-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('tax_id', models.CharField(max_length=50, unique=True)),
                ('vat_id', models.CharField(max_length=50, unique=True)),
                ('reg_id', models.CharField(max_length=50, unique=True)),
                ('incorporation_date', models.DateField()),
            ],
        ),
    ]
