# Generated by Django 4.1.13 on 2024-05-19 17:58

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='', max_length=255, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('blurb', models.TextField(blank=True, default='')),
                ('desc', models.TextField(blank=True, default='')),
                ('stock', models.IntegerField(default=0, validators=[shop.models.validate_non_negative])),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, validators=[shop.models.validate_non_negative])),
                ('brand', models.CharField(default='cadence', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('blocked', models.BooleanField(default=False)),
                ('collection', models.CharField(choices=[('HANDTOOLS', 'Hand Tools'), ('POWERTOOLS', 'Power Tools'), ('TESTING', 'Testing Equipment'), ('CONSUMABLES', 'Consumables'), ('STORAGE', 'Storage'), ('WEARABLE', 'Wearables')], default='HANDTOOLS', max_length=20)),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('DIGITAL', 'Digital'), ('SUBSCRIPTION', 'Subscription'), ('LABOUR', 'Labour')], default='PHYSICAL', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
