# Generated by Django 4.1.13 on 2024-05-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='url',
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
