# Generated by Django 4.1.13 on 2024-05-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('order_number', models.TextField()),
                ('message', models.TextField()),
                ('reference_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
