# Generated by Django 4.1.13 on 2024-05-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_profile_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
