# Generated by Django 4.1.13 on 2024-05-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_salesorder_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
