# Generated by Django 4.1.13 on 2024-05-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_salesorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
