# Generated by Django 4.1.13 on 2024-05-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_media_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='seo_desc',
        ),
        migrations.AddField(
            model_name='product',
            name='seo_keys',
            field=models.TextField(blank=True, default=''),
        ),
    ]
